version: '3.8'

services:
  # InfluxDB v1.8 for k6 metrics (k6 native support)
  influxdb:
    image: influxdb:1.8
    container_name: influxdb-k6
    ports:
      - "8086:8086"
    networks:
      - k6-network
      - monitoring-network
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6
      - INFLUXDB_USER=k6
      - INFLUXDB_USER_PASSWORD=k6
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # k6 Performance Testing Tool
  k6:
    image: grafana/k6:latest
    container_name: k6-performance
    networks:
      - k6-network
    volumes:
      - ./k6:/scripts
      - ./k6/results:/results
    environment:
      - K6_INFLUXDB_USERNAME=k6
      - K6_INFLUXDB_PASSWORD=k6
    command: run --out influxdb=http://influxdb:8086/k6 /scripts/load-test.js
    depends_on:
      influxdb:
        condition: service_healthy
    profiles:
      - test

volumes:
  influxdb_data:
    driver: local
    name: nomodel_influxdb_data

networks:
  k6-network:
    driver: bridge
    name: nomodel_k6_network
  monitoring-network:
    external: true