management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      maximum-expected-value:
        http.server.requests: 10s

# SpringDoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  show-actuator: true
  
# AOP 모니터링 설정
monitoring:
  aop:
    # Service 성능 모니터링 설정
    service:
      enabled: true
      slow-method-threshold-ms: 1000
      warning-method-threshold-ms: 500
      statistics-log-interval: 100
    
    # Slow Query 감지 설정
    slow-query:
      enabled: true
      threshold-ms: 1000
      warning-threshold-ms: 500
      history-size: 100
      report-interval: 10
      optimization-suggestions: true
    
    # 감사 로깅 설정
    audit:
      enabled: true
      mask-sensitive-data: true
      include-stack-trace: true
      critical-action-alert: true
      max-parameter-length: 1000

# 로깅 설정
logging:
  level:
    org.springframework.boot.actuator: DEBUG
    com.example.nomodel._core.aop: INFO
    # Service 성능 로깅
    com.example.nomodel._core.aop.ServicePerformanceAspect: INFO
    # Slow Query 로깅  
    com.example.nomodel._core.aop.SlowQueryDetectorAspect: INFO
    # 감사 로깅
    com.example.nomodel._core.aop.AuditLoggingAspect: INFO