server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Spring Boot application logs from file
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot
          __path__: /logs/*.json
    pipeline_stages:
      - json:
          expressions:
            level: level
            application: application
            message: message
            class_name: class_name
            method_name: method_name
            full_method_name: full_method_name
            layer: layer
            execution_id: execution_id
            execution_time_ms: execution_time_ms
            status: status
            error_message: error_message
            error_class: error_class
            http_method: http_method
            request_uri: request_uri
      - labels:
          level:
          application:
          layer:
          status:
          class_name:
          method_name:
      - pack:
          labels:
            - full_method_name
            - execution_id
            - execution_time_ms
            - error_message
            - error_class
            - http_method
            - request_uri

  # System logs (optional)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /host/var/log/*.log