server:
  servlet:
    context-path: /api

spring:
  profiles:
    active:
      - local
  config:
    import: 
      - optional:file:.env[.properties]
      - optional:classpath:config/application-docker.yml
      - optional:classpath:config/application-monitoring.yml
      - optional:classpath:config/external-services.yml

# 애플리케이션 설정
app:
  batch:
    aimodel-index:
      enabled: true  # AIModel 인덱싱 배치 활성화 (운영환경에서는 false로 설정 가능)