server:
  servlet:
    context-path: /api

spring:
  profiles:
    active:
      - prod
  config:
    import: 
      - optional:file:.env[.properties]
      - optional:classpath:config/application-docker.yml
      - optional:classpath:config/application-monitoring.yml