apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        - name: trace_id
          url: http://jaeger:16686/trace/$${__value.raw}
    secureJsonData: {}

  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: false
    editable: true
    database: k6
    user: k6
    jsonData:
      httpMode: GET
      keepCookies: []
    secureJsonData:
      password: k6